/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ProcessController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramses
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    String Tarjeta;
    
    public PantallaPrincipal() {
        initComponents();
        jPanelConsulta.setVisible(false);
        jPanelRetiro.setVisible(false);
        jPanelDeposito.setVisible(false);
        jPanelCambioClave.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsulta = new javax.swing.JButton();
        jButtonRetiro = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jButtonCambioClave = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelPrincipal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelRetiro = new javax.swing.JPanel();
        jLabelRetiro = new javax.swing.JLabel();
        jTextFieldRetiro = new javax.swing.JTextField();
        jButtonAcepRetiro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelDeposito = new javax.swing.JPanel();
        jLabelDeposito = new javax.swing.JLabel();
        jTextFieldDeposito = new javax.swing.JTextField();
        jButtonAcepDeposito = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanelCambioClave = new javax.swing.JPanel();
        jLabelClave1 = new javax.swing.JLabel();
        jLabelClave2 = new javax.swing.JLabel();
        jButtonAcepCambio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldClave2 = new javax.swing.JPasswordField();
        jPasswordFieldClave3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco SAIME Yajés Fuenmayor");
        getContentPane().setLayout(null);

        jButtonConsulta.setText("Consulta");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsulta);
        jButtonConsulta.setBounds(490, 40, 130, 23);

        jButtonRetiro.setText("Retiro");
        jButtonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetiro);
        jButtonRetiro.setBounds(490, 70, 130, 23);

        jButtonDeposito.setText("Deposito");
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeposito);
        jButtonDeposito.setBounds(490, 100, 130, 23);

        jButtonCambioClave.setText("Cambio Clave");
        jButtonCambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambioClaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambioClave);
        jButtonCambioClave.setBounds(490, 130, 130, 23);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(490, 160, 130, 23);

        jPanelConsulta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelConsulta.setLayout(null);

        jLabelSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSaldo.setText("Su Saldo es:");
        jLabelSaldo.setToolTipText("");
        jPanelConsulta.add(jLabelSaldo);
        jLabelSaldo.setBounds(30, 60, 120, 20);

        jTextFieldSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldSaldo.setForeground(new java.awt.Color(0, 102, 204));
        jPanelConsulta.add(jTextFieldSaldo);
        jTextFieldSaldo.setBounds(290, 60, 140, 23);

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Banco Saime Yajes Fuenmayor");
        jLabel1.setToolTipText("");
        jPanelConsulta.add(jLabel1);
        jLabel1.setBounds(30, 8, 420, 30);

        getContentPane().add(jPanelConsulta);
        jPanelConsulta.setBounds(10, 10, 460, 200);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        jPanelPrincipal.setLayout(null);

        jLabelPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrincipal.setForeground(new java.awt.Color(0, 153, 153));
        jLabelPrincipal.setText("Bienvenido al Cajero Automático");
        jLabelPrincipal.setToolTipText("");
        jPanelPrincipal.add(jLabelPrincipal);
        jLabelPrincipal.setBounds(80, 60, 310, 80);

        jLabel5.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Banco Saime Yajes Fuenmayor");
        jLabel5.setToolTipText("");
        jPanelPrincipal.add(jLabel5);
        jLabel5.setBounds(30, 8, 420, 30);

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(10, 10, 460, 200);

        jPanelRetiro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRetiro.setPreferredSize(new java.awt.Dimension(460, 200));
        jPanelRetiro.setRequestFocusEnabled(false);
        jPanelRetiro.setLayout(null);

        jLabelRetiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRetiro.setText("Introduzca el monto a Retirar:");
        jPanelRetiro.add(jLabelRetiro);
        jLabelRetiro.setBounds(30, 60, 250, 22);

        jTextFieldRetiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRetiro.setForeground(new java.awt.Color(0, 102, 204));
        jPanelRetiro.add(jTextFieldRetiro);
        jTextFieldRetiro.setBounds(290, 60, 140, 23);

        jButtonAcepRetiro.setText("Aceptar");
        jButtonAcepRetiro.setToolTipText("");
        jButtonAcepRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepRetiroActionPerformed(evt);
            }
        });
        jPanelRetiro.add(jButtonAcepRetiro);
        jButtonAcepRetiro.setBounds(180, 160, 71, 23);

        jLabel2.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 18)); // NOI18N
        jLabel2.setText("Banco Saime Yajes Fuenmayor");
        jLabel2.setToolTipText("");
        jPanelRetiro.add(jLabel2);
        jLabel2.setBounds(30, 8, 420, 30);

        getContentPane().add(jPanelRetiro);
        jPanelRetiro.setBounds(10, 10, 460, 200);

        jPanelDeposito.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDeposito.setPreferredSize(new java.awt.Dimension(460, 200));
        jPanelDeposito.setRequestFocusEnabled(false);
        jPanelDeposito.setLayout(null);

        jLabelDeposito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDeposito.setText("Introduzca el monto a Depositar:");
        jPanelDeposito.add(jLabelDeposito);
        jLabelDeposito.setBounds(30, 60, 280, 22);

        jTextFieldDeposito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDeposito.setForeground(new java.awt.Color(0, 102, 204));
        jPanelDeposito.add(jTextFieldDeposito);
        jTextFieldDeposito.setBounds(300, 60, 130, 23);

        jButtonAcepDeposito.setText("Aceptar");
        jButtonAcepDeposito.setToolTipText("");
        jButtonAcepDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepDepositoActionPerformed(evt);
            }
        });
        jPanelDeposito.add(jButtonAcepDeposito);
        jButtonAcepDeposito.setBounds(180, 160, 71, 23);

        jLabel4.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 18)); // NOI18N
        jLabel4.setText("Banco Saime Yajes Fuenmayor");
        jLabel4.setToolTipText("");
        jPanelDeposito.add(jLabel4);
        jLabel4.setBounds(30, 8, 420, 30);

        getContentPane().add(jPanelDeposito);
        jPanelDeposito.setBounds(10, 10, 460, 200);

        jPanelCambioClave.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCambioClave.setLayout(null);

        jLabelClave1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClave1.setText("Introduzca la nueva clave:");
        jLabelClave1.setToolTipText("");
        jPanelCambioClave.add(jLabelClave1);
        jLabelClave1.setBounds(30, 60, 220, 22);

        jLabelClave2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClave2.setText("Repita la nueva clave:");
        jPanelCambioClave.add(jLabelClave2);
        jLabelClave2.setBounds(30, 100, 190, 22);

        jButtonAcepCambio.setText("Aceptar");
        jButtonAcepCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepCambioActionPerformed(evt);
            }
        });
        jPanelCambioClave.add(jButtonAcepCambio);
        jButtonAcepCambio.setBounds(180, 160, 71, 23);

        jLabel3.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 18)); // NOI18N
        jLabel3.setText("Banco Saime Yajes Fuenmayor");
        jLabel3.setToolTipText("");
        jPanelCambioClave.add(jLabel3);
        jLabel3.setBounds(30, 8, 420, 30);

        jPasswordFieldClave2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanelCambioClave.add(jPasswordFieldClave2);
        jPasswordFieldClave2.setBounds(290, 100, 140, 23);

        jPasswordFieldClave3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanelCambioClave.add(jPasswordFieldClave3);
        jPasswordFieldClave3.setBounds(290, 60, 140, 23);

        getContentPane().add(jPanelCambioClave);
        jPanelCambioClave.setBounds(10, 10, 460, 200);

        setBounds(0, 0, 651, 263);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        // TODO add your handling code here:
        jPanelPrincipal.setVisible(false);
        jPanelConsulta.setVisible(true);
        jPanelRetiro.setVisible(false);
        jPanelDeposito.setVisible(false);
        jPanelCambioClave.setVisible(false);
        
        ProcessController pa = new ProcessController();
        jTextFieldSaldo.setText(String.valueOf(pa.consultarSaldo(Tarjeta)));
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jButtonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetiroActionPerformed
        // TODO add your handling code here:
        jPanelPrincipal.setVisible(false);
        jPanelConsulta.setVisible(false);
        jPanelRetiro.setVisible(true);
        jPanelDeposito.setVisible(false);
        jPanelCambioClave.setVisible(false);
    }//GEN-LAST:event_jButtonRetiroActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        // TODO add your handling code here:
        jPanelPrincipal.setVisible(false);
        jPanelConsulta.setVisible(false);
        jPanelRetiro.setVisible(false);
        jPanelDeposito.setVisible(true);
        jPanelCambioClave.setVisible(false);
    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonCambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambioClaveActionPerformed
        // TODO add your handling code here:
        jPanelPrincipal.setVisible(false);
        jPanelConsulta.setVisible(false);
        jPanelRetiro.setVisible(false);
        jPanelDeposito.setVisible(false);
        jPanelCambioClave.setVisible(true);
    }//GEN-LAST:event_jButtonCambioClaveActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        //dispose();
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?");
        if(confirmar==JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAcepRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcepRetiroActionPerformed
        String monto = String.valueOf(jTextFieldRetiro.getText());
        
        ProcessController pa = new ProcessController();
        pa.retirarMonto(Tarjeta, monto);
        jTextFieldRetiro.setText("");
    }//GEN-LAST:event_jButtonAcepRetiroActionPerformed

    private void jButtonAcepDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcepDepositoActionPerformed
        // TODO add your handling code here:
        String monto = String.valueOf(jTextFieldDeposito.getText());

        ProcessController pa = new ProcessController();
        pa.depositarMonto(Tarjeta, monto);
        jTextFieldDeposito.setText("");
    }//GEN-LAST:event_jButtonAcepDepositoActionPerformed

    private void jButtonAcepCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcepCambioActionPerformed
        // TODO add your handling code here:
        String clave = String.valueOf(jPasswordFieldClave2.getText());
        String clave2 = String.valueOf(jPasswordFieldClave3.getText());
        JFrame frame = new JFrame("");
        
        if (clave.equals(clave2)){
            ProcessController pa = new ProcessController();
            pa.cambioClave(Tarjeta, clave);
            JOptionPane.showMessageDialog(frame,"Cambio de Clave Satisfactorio","",JOptionPane.INFORMATION_MESSAGE); 
        }else
            JOptionPane.showMessageDialog(frame,"Las claves no son las mismas, deben ser iguales","",JOptionPane.INFORMATION_MESSAGE); 
            jPasswordFieldClave2.setText("");
            jPasswordFieldClave3.setText("");
    }//GEN-LAST:event_jButtonAcepCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcepCambio;
    private javax.swing.JButton jButtonAcepDeposito;
    private javax.swing.JButton jButtonAcepRetiro;
    private javax.swing.JButton jButtonCambioClave;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonRetiro;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClave1;
    private javax.swing.JLabel jLabelClave2;
    private javax.swing.JLabel jLabelDeposito;
    private javax.swing.JLabel jLabelPrincipal;
    private javax.swing.JLabel jLabelRetiro;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JPanel jPanelCambioClave;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelDeposito;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRetiro;
    private javax.swing.JPasswordField jPasswordFieldClave2;
    private javax.swing.JPasswordField jPasswordFieldClave3;
    private javax.swing.JTextField jTextFieldDeposito;
    private javax.swing.JTextField jTextFieldRetiro;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
